version: '3'

vars:
  PYTHON: .venv/bin/python

tasks:
  # Backend tasks
  backend:setup:
    desc: Setup backend virtual environment and install dependencies
    dir: backend
    cmds:
      - uv venv ../.venv
      - uv pip install -e .
      - uv pip install -e ".[dev]"
      - echo "Backend setup complete"

  backend:dev:
    desc: Start backend development server
    dir: backend
    deps:
      - backend:setup
    cmds:
      - ../.venv/bin/uvicorn prompt_butler.main:app --reload --host 0.0.0.0 --port 8000

  frontend:setup:
    desc: Setup frontend and install dependencies
    dir: frontend
    cmds:
      - npm install
      - echo "Frontend setup complete"

  frontend:dev:
    desc: Start frontend development server
    dir: frontend
    deps:
      - frontend:setup
    cmds:
      - npm run dev

  backend:test:
    desc: Run backend tests
    cmds:
      - .venv/bin/pytest backend/tests -v --tb=short

  backend:lint:
    desc: Run backend linting (ruff)
    cmds:
      - .venv/bin/ruff check backend

  frontend:build:
    desc: Build frontend for production
    dir: frontend
    cmds:
      - npm run build

  frontend:lint:
    desc: Run frontend linting (eslint)
    dir: frontend
    cmds:
      - npm run lint

  test:
    desc: Run all tests
    cmds:
      - task: backend:test

  lint:
    desc: Run all linters
    cmds:
      - task: backend:lint
      - task: frontend:lint

  build:
    desc: Build all components
    cmds:
      - task: frontend:build

  dev:
    desc: Start all development servers in parallel
    deps:
      - backend:setup
      - frontend:setup
    cmds:
      - |
        trap 'kill 0' EXIT
        task backend:dev &
        task frontend:dev &
        wait
