version: '3'

vars:
  PYTHON: .venv/bin/python

includes:
  feature:
    taskfile: ./workflow/Taskfile.yml

tasks:
  # Root-level setup
  setup:
    desc: Install dependencies for root-level scripts and utilities
    cmds:
      - echo "Setting up root-level dependencies..."
      - uv venv
      - uv pip install -r workflow/requirements.txt
      - echo "Project setup complete."
  
  # Backend tasks
  backend:setup:
    desc: Setup backend virtual environment and install dependencies
    dir: backend
    cmds:
      - uv venv ../.venv
      - uv pip install -e .
      - uv pip install -e ".[dev]"
      - echo "Backend setup complete"
  
  backend:dev:
    desc: Start backend development server
    dir: backend
    deps:
      - backend:setup
    cmds:
      - ../.venv/bin/uvicorn main:app --reload --host 0.0.0.0 --port 8000
  
  dev:
    desc: Start all development servers
    deps:
      - backend:dev